version: 2

run:
  timeout: 5m
  tests: true
  go: "1.24"
  build-tags:
    - integration

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - ineffassign
    - misspell
