version: '3'

tasks:
  preflight:
    desc: Run all preflight checks before shipping
    cmds:
      - task: fmt
      - task: lint
      - task: test
      - echo "✅ All preflight checks passed!"

  fmt:
    desc: Format all Go code
    cmds:
      - go fmt ./...

  lint:
    desc: Run golangci-lint
    cmds:
      - golangci-lint run --config .golangci.yml ./...

  test:
    desc: Run all unit tests
    cmds:
      - go test -short ./src/...

  test-integration:
    desc: Run integration tests
    cmds:
      - go test -v ./src/... -tags=integration

  build:
    desc: Build the CLI extension
    cmds:
      - go build -o bin/azd-app{{exeExt}} ./src/cmd/app

  install:
    desc: Install the extension locally
    deps: [build]
    cmds:
      - azd extension uninstall app || true
      - azd extension install --path .

  uninstall:
    desc: Uninstall the extension
    cmds:
      - azd extension uninstall app

  clean:
    desc: Clean build artifacts
    cmds:
      - cmd: rm -rf bin/
        platforms: [linux, darwin]
      - cmd: Remove-Item -Path bin/ -Recurse -Force -ErrorAction SilentlyContinue
        platforms: [windows]

  coverage:
    desc: Run tests with coverage
    cmds:
      - go test -short -coverprofile=coverage.out ./src/...
      - go tool cover -html=coverage.out -o coverage.html
      - echo "Coverage report generated at coverage.html"
