// Package docsgate verifies that the shipped CLI surface stays documented.
//
// The gate answers two different questions, and it keeps them separate on
// purpose because they fail for different reasons and deserve different
// treatment.
//
// Structural rules compare the live Cobra command tree against
// cli/docs/cli-reference.md. Every visible command needs a reference section, an
// overview row, a detail doc, and a row for every visible flag. These rules look
// at repository state rather than at a diff, so they cannot be sidestepped by
// splitting a change across pull requests, and they never fire on a pure
// refactor. They are not skippable.
//
// Change rules compare a pull request's changed files against a small table of
// path mappings, catching edits that alter behavior without adding or removing a
// flag. Renaming an output column is the motivating example. These rules are
// heuristics, so they honor an explicit, recorded escape hatch.
//
// The command tree is read from `azd app metadata`, the hidden command the azd
// extension framework already provides. Reading the shipped binary rather than
// parsing Go source means the gate can never drift from what users actually get.
package docsgate

import (
	"bytes"
	"encoding/json"
	"errors"
	"fmt"
	"sort"
	"strings"
)

// cobraBuiltins are generated by Cobra rather than authored in this repository,
// so the gate never demands documentation for them. Documenting them anyway is
// allowed; `completion` already has a reference section.
var cobraBuiltins = map[string]bool{
	"help":       true,
	"completion": true,
}

// Flag is a single flag on a command, as reported by `azd app metadata`.
type Flag struct {
	Name        string `json:"name"`
	Shorthand   string `json:"shorthand"`
	Description string `json:"description"`
	Type        string `json:"type"`
	Default     string `json:"default"`
	Hidden      bool   `json:"hidden"`
	Deprecated  string `json:"deprecated"`
}

// Command is one node of the CLI command tree.
type Command struct {
	Name        []string  `json:"name"`
	Short       string    `json:"short"`
	Long        string    `json:"long"`
	Usage       string    `json:"usage"`
	Flags       []Flag    `json:"flags"`
	Hidden      bool      `json:"hidden"`
	Deprecated  string    `json:"deprecated"`
	Subcommands []Command `json:"subcommands"`
}

// Metadata is the top level document emitted by `azd app metadata`.
type Metadata struct {
	SchemaVersion string    `json:"schemaVersion"`
	ID            string    `json:"id"`
	Commands      []Command `json:"commands"`
}

// ErrEmptyCommandTree reports metadata that parsed but described no commands.
//
// Validating against an empty tree would pass every structural rule while
// proving nothing, so the gate refuses to continue.
var ErrEmptyCommandTree = errors.New("CLI metadata contained no commands")

// ParseMetadata decodes the JSON emitted by `azd app metadata`.
//
// The metadata command prints one JSON document, but callers routinely capture
// combined output where a banner or warning precedes it. Trimming to the first
// opening brace keeps the gate from failing on unrelated noise.
func ParseMetadata(raw []byte) (*Metadata, error) {
	trimmed := raw
	if idx := bytes.IndexByte(raw, '{'); idx > 0 {
		trimmed = raw[idx:]
	}

	var md Metadata
	if err := json.Unmarshal(trimmed, &md); err != nil {
		return nil, fmt.Errorf("failed to parse CLI metadata JSON: %w", err)
	}
	if len(md.Commands) == 0 {
		return nil, ErrEmptyCommandTree
	}
	return &md, nil
}

// CommandRef is a flattened command carrying the identity the docs use.
type CommandRef struct {
	// Path holds the command words below the root, such as ["notifications", "list"].
	Path []string
	// Hidden is true when the command or any ancestor is hidden.
	Hidden bool
	// Builtin is true when Cobra generated the command.
	Builtin bool
	// Short is the one line summary shown in help output.
	Short string
	// Flags holds every flag Cobra resolves for the command, including inherited ones.
	Flags []Flag
}

// Name renders the command the way cli-reference.md heads its sections, such as
// "notifications list".
func (c CommandRef) Name() string { return strings.Join(c.Path, " ") }

// Slug renders the command the way cli/docs/commands/ names files, such as
// "notifications-list".
func (c CommandRef) Slug() string { return strings.Join(c.Path, "-") }

// Root returns the top level command this one belongs to.
func (c CommandRef) Root() string { return c.Path[0] }

// TopLevel reports whether the command sits directly under the root.
//
// Top level commands carry the documentation burden: they get a reference
// section, an overview row, and a detail doc. Subcommands are documented inside
// their parent, which is how cli-reference.md already reads.
func (c CommandRef) TopLevel() bool { return len(c.Path) == 1 }

// Leaf returns the final word of the command path, which is how a parent
// section's Subcommands table names it.
func (c CommandRef) Leaf() string { return c.Path[len(c.Path)-1] }

// DocumentedFlags returns the flags a reader is entitled to find in the docs:
// everything neither hidden nor deprecated, sorted by name.
//
// Deprecated flags are excluded because documenting a flag on its way out would
// steer readers toward it.
func (c CommandRef) DocumentedFlags() []Flag {
	out := make([]Flag, 0, len(c.Flags))
	for _, f := range c.Flags {
		if f.Hidden || f.Deprecated != "" {
			continue
		}
		out = append(out, f)
	}
	sort.Slice(out, func(i, j int) bool { return out[i].Name < out[j].Name })
	return out
}

// flatten walks the tree depth first and returns every command, sorted by name.
//
// A command inherits hidden from its ancestors: subcommands of a hidden command
// never appear in help output, so requiring docs for them would be noise.
func (m *Metadata) flatten() []CommandRef {
	var out []CommandRef
	var walk func(cmds []Command, parentHidden bool)
	walk = func(cmds []Command, parentHidden bool) {
		for _, c := range cmds {
			if len(c.Name) == 0 {
				continue
			}
			hidden := parentHidden || c.Hidden
			out = append(out, CommandRef{
				Path:    append([]string(nil), c.Name...),
				Hidden:  hidden,
				Builtin: cobraBuiltins[c.Name[0]],
				Short:   c.Short,
				Flags:   c.Flags,
			})
			walk(c.Subcommands, hidden)
		}
	}
	walk(m.Commands, false)
	sort.Slice(out, func(i, j int) bool { return out[i].Name() < out[j].Name() })
	return out
}

// DocumentableCommands returns the commands the gate requires documentation
// for: visible and authored in this repository.
func (m *Metadata) DocumentableCommands() []CommandRef {
	var out []CommandRef
	for _, c := range m.flatten() {
		if c.Hidden || c.Builtin {
			continue
		}
		out = append(out, c)
	}
	return out
}

// KnownCommandSlugs returns every slug in the tree, hidden and built-in
// included.
//
// Orphan detection uses the full set so documenting a hidden command such as
// `mcp` stays legal, while a doc for a command that no longer exists is still
// reported.
func (m *Metadata) KnownCommandSlugs() map[string]bool {
	out := make(map[string]bool)
	for _, c := range m.flatten() {
		out[c.Slug()] = true
	}
	return out
}
